INSERT quest_template_addon SET ID = 61360;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 61360 ;
INSERT quest_template_addon SET ID = 2203;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 2203  ;
INSERT quest_template_addon SET ID = 736;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 736  ;
INSERT quest_template_addon SET ID = 2501;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 2501  ;
INSERT quest_template_addon SET ID = 3781;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 3781  ;
INSERT quest_template_addon SET ID = 3449;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 3449  ;
INSERT quest_template_addon SET ID = 63134;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63134   ;
INSERT quest_template_addon SET ID = 63133;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63133  ;
INSERT quest_template_addon SET ID = 63132;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63132  ;
INSERT quest_template_addon SET ID = 63159;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63159  ;
INSERT quest_template_addon SET ID = 63158;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63158  ;
INSERT quest_template_addon SET ID = 63155;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63155  ;
INSERT quest_template_addon SET ID = 63153;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63153  ;
INSERT quest_template_addon SET ID = 63145;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63145  ;
INSERT quest_template_addon SET ID = 63163;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63163  ;
INSERT quest_template_addon SET ID = 63161;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63161  ;
INSERT quest_template_addon SET ID = 63140;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63140  ;
INSERT quest_template_addon SET ID = 63160;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 63160  ;
INSERT quest_template_addon SET ID = 58751;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 58751  ;
INSERT quest_template_addon SET ID = 62984;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62984  ;
INSERT quest_template_addon SET ID = 62970;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62970  ;
INSERT quest_template_addon SET ID = 62261;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62261  ;
INSERT quest_template_addon SET ID = 62804;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62804  ;
INSERT quest_template_addon SET ID = 61996;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 61996  ;
INSERT quest_template_addon SET ID = 1148;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 1148  ;
INSERT quest_template_addon SET ID = 26758;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 26758  ;
INSERT quest_template_addon SET ID = 61511;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 61511  ;
INSERT quest_template_addon SET ID = 59126;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 59126  ;
INSERT quest_template_addon SET ID = 7647;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 7647  ;
INSERT quest_template_addon SET ID = 62622;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62622  ;
INSERT quest_template_addon SET ID = 62621;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62621  ;
INSERT quest_template_addon SET ID = 62620;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62620  ;
INSERT quest_template_addon SET ID = 62486;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62486  ;
INSERT quest_template_addon SET ID = 62483;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62483  ;
INSERT quest_template_addon SET ID = 62440;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62440  ;
INSERT quest_template_addon SET ID = 62439;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62439  ;
INSERT quest_template_addon SET ID = 62438;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62438  ;
INSERT quest_template_addon SET ID = 62436;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62436  ;
INSERT quest_template_addon SET ID = 62431;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62431  ;
INSERT quest_template_addon SET ID = 62430;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62430  ;
INSERT quest_template_addon SET ID = 62428;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62428  ;
INSERT quest_template_addon SET ID = 62425;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62425  ;
INSERT quest_template_addon SET ID = 62423;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62423  ;
INSERT quest_template_addon SET ID = 62422;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62422  ;
INSERT quest_template_addon SET ID = 62250;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62250  ;
INSERT quest_template_addon SET ID = 62246;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62246  ;
INSERT quest_template_addon SET ID = 62189;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62189  ;
INSERT quest_template_addon SET ID = 62184;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62184  ;
INSERT quest_template_addon SET ID = 62183;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62183 ;
INSERT quest_template_addon SET ID = 62182;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62182;
INSERT quest_template_addon SET ID = 62085;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62085; 
INSERT quest_template_addon SET ID = 62052;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62052; 
INSERT quest_template_addon SET ID = 61878;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 61878;   
INSERT quest_template_addon SET ID = 62774;
UPDATE quest_template_addon SET ProvidedItemCount=1 WHERE id = 62774;