--DK starting ZONE Objects phases

update gameobject set phaseid = 169 WHERE guid = 29493;
update gameobject set phaseid = 169 WHERE guid = 29500;
update gameobject set phaseid = 169 WHERE guid = 30005;
update gameobject set phaseid = 169 WHERE guid = 29468;
update gameobject set phaseid = 169 WHERE guid = 29486;
update gameobject set phaseid = 169 WHERE guid = 29495;
update gameobject set phaseid = 169 WHERE guid = 29501;
update gameobject set phaseid = 169 WHERE guid = 29499;

update gameobject set phaseid = 169 WHERE guid = 29491;
update gameobject set phaseid = 169 WHERE guid = 29467;
update gameobject set phaseid = 169 WHERE guid = 29490;

update gameobject set phaseid = 169 WHERE guid = 191650;
update gameobject set phaseid = 169 WHERE guid = 191583;
update gameobject set phaseid = 169 WHERE guid = 191584;